### ISSUE TITLE
[request] Provide ONNX models or provide info about the models.

### ISSUE THREAD

**Issue by gaocegege** [vinx13/tvm-cuda-benchmark#1]
Now the https://github.com/vinx13/tvm-cuda-benchmark/tree/master/onnx_model is empty. But the models are used in TensorRT benchmarks. Different implementations may result in different metrics. Thus request to add the models or provide the info of the models. For example, the reference implementation in Caffe2 or PyTorch.

Thanks

**Comment by vinx13** [comment]
TensorRT takes onnx model as input. When you run `run_tensorrt.py`, onnx models will be generated from mxnet. I'll add a note.

**Comment by gaocegege** [comment]
Thanks
