### ISSUE TITLE
Incompatibility with TVM 0.7.dev1

### ISSUE THREAD

**Issue by Screeen** [vinx13/tvm-cuda-benchmark#10]
Hi, unfortunately the provided code is not compatible with the TVM 0.7.dev1

In [tune_relay_int8_cuda](https://github.com/vinx13/tvm-cuda-int8-benchmark/blob/master/tune_relay_int8_cuda.py), at line 225, you use: 

`tsk = autotvm.task.create(tasks[i].name, tasks[i].args,
                                      tasks[i].target, tasks[i].target_host, 'int8')`

But the current implementation of `autotvm.task.create` is `def create(task_name, args, target, target_host=None)`. As you can see, the `template_key=int8` argument has been removed.

How to compile using `int8` in the latest TVM version?

**Comment by cailun01** [comment]
> Hi, unfortunately the provided code is not compatible with the TVM 0.7.dev1
> 
> In [tune_relay_int8_cuda](https://github.com/vinx13/tvm-cuda-int8-benchmark/blob/master/tune_relay_int8_cuda.py), at line 225, you use:
> 
> `tsk = autotvm.task.create(tasks[i].name, tasks[i].args, tasks[i].target, tasks[i].target_host, 'int8')`
> 
> But the current implementation of `autotvm.task.create` is `def create(task_name, args, target, target_host=None)`. As you can see, the `template_key=int8` argument has been removed.
> 
> How to compile using `int8` in the latest TVM version?

As far as I'm concerned, although `autotvm.task.create`  only has 4 arguments now, the program still can run.

**Comment by vinx13** [comment]
fixed by #11
