### ISSUE TITLE
 Unrecognized attribute: spatial for operator BatchNormalization

### ISSUE THREAD

**Issue by hewumars** [vinx13/tvm-cuda-benchmark#2]
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: spatial for operator BatchNormalization
how to solve this?

**Comment by vinx13** [comment]
Likely this is a onnx version incompatibility issue. You can try removing your onnx model files and regenerating them, or install onnx-1.3
see https://github.com/onnx/onnx/commit/fd60104394fa353e1762f44ecad1b2166e33deef

**Comment by hewumars** [comment]
Thank you, I have already solved it.But The experimental results  are different from yours with Nvidia1080Ti.
![image](https://user-images.githubusercontent.com/7970022/59486437-dffd9300-8eab-11e9-9e56-f70e2f620ffe.png)
![image](https://user-images.githubusercontent.com/7970022/59486460-eb50be80-8eab-11e9-9c6b-0377a0974403.png)

**Comment by vinx13** [comment]
The tuning logs are only for 1080. You need to tune by yourself on 1080ti to obtain the best result.
