### ISSUE TITLE
Configs about auto-tuning an int8 CNN

### ISSUE THREAD

**Issue by zfonemore** [vinx13/tvm-cuda-benchmark#3]
Hi, I have tried auto-tuning an int8 ResNet, but I did not get a good performance. I find that configs in your benchmark are different from configs in float CNN auto-tuning. I want to know how to set configs to tune a fast int8 CNN, thanks!

**Comment by vinx13** [comment]
```
{
    'tuner': 'xgb',
    'n_trial': 2000,
    'early_stopping': 1200,
    'sa_iter': 800
}

tuner = XGBTuner(tsk, optimizer=SimulatedAnnealingOptimizer(tsk, n_iter=sa_iter))
```
Also make sure that tasks are created with `template_key='int8' for those input and output channels are divisible by 4.

**Comment by zfonemore** [comment]
Thanks! Have you tested int8 ResNet-50 with larger batch size such as 64? Could you share the auto-tune code of this benchmark?

**Comment by vinx13** [comment]
I didn't try batch=64 or larger. Auto-tune code for this benchmark is a modification from the autotvm tutorial but it is not available now

**Comment by zfonemore** [comment]
Ok, thanks for your help!
