### ISSUE TITLE
Shape of int8 conv is NCHWc.

### ISSUE THREAD

**Issue by zfonemore** [vinx13/tvm-cuda-benchmark#4]
Hi, I find that output shape of int8 conv is NCHWc. If I want to use int8 conv, I have to convert output shape from NCHWc to NCHW, which is time-consuming. Do you have int8 conv function that support NCHW?

**Comment by vinx13** [comment]
NCHWc is required to achieve good perf for int8. I would suggest converting the rest of your network to NCHWc if that is the bottleneck. In most cases, layout transformation only happens in the first layer and the last layer of the int8 network, so the overhead should be small.

**Comment by zfonemore** [comment]
Ok, I get it. Do you support int8 conv with dilation larger than 1?

**Comment by vinx13** [comment]
Yes it is already supported
