### ISSUE TITLE
How to add quantize op in int8 convolution op?

### ISSUE THREAD

**Issue by zfonemore** [vinx13/tvm-cuda-benchmark#6]
Hi, I want to add quantize op in int8 convolution op, and I add quantizeop like this(qi_scale is an input placeholder):
```python
quantize_data = tvm.compute((batch, channels, height, width),
                           lambda n, c, h, w: data[n, c, h, w] * qi_scale[0], name="quantize_data")
```
But I got mistake "Cannot find allocated buffer for placeholder(placeholder, 0x7f34625feb50)',)" when auto-tuning. I think this mistake is caused by schedule, and I tried to add some code in schedule, but it did not work.

**Comment by vinx13** [comment]
It should be inlined. You can take a look how padding on data is handled in the schedule.

**Comment by zfonemore** [comment]
I tried using ```s[quantize].compute_inline()```, but it did not work. I do not know how to make this quantize op inline.

**Comment by vinx13** [comment]
It should work. It will be complicated if both quantize op and padding are present. In this case you need to make sure which op are being inlined.

在 2019年7月30日，下午4:50，zfonemore <notifications@github.com<mailto:notifications@github.com>> 写道：


I tried using s[quantize].compute_inline(), but it did not work. I do not know how to make this quantize op inline.

**Comment by zfonemore** [comment]
I have solved this problem. Thanks for your help!
