### ISSUE TITLE
Could you tell me how to tune quantized int8 model?

### ISSUE THREAD

**Issue by mingwayzhang** [vinx13/tvm-cuda-benchmark#7]
Hi,

I am trying to tune the int8 conv2d layers myself in my models, since they are in non-standard shape.

I try to use the tuning code in tutorial (tune_relay_cuda.py) with minor modification by adding quantization. However, I cannot generate even meaningful result. Is there anything I am missing?

I also noticed in previously closed issue that in8 conv2d has to be in NCHWc. Is that required for tuning? If so, how did you get the good results of int8 in NCHW (in your logs)?

Your help is urgently needed! Appreciate your response. Thanks.

**Comment by vinx13** [comment]
int8 conv2d has to be in NCHWc to get good perf, AlterOpLayout pass will transform NCHW to NCHWc
https://github.com/vinx13/tvm-cuda-int8-benchmark/blob/master/tune_relay_int8_cuda.py

**Comment by mingwayzhang** [comment]
Hi Wuwei,

There is still one question on my side. My model input channel is 512 (which is fine) but the output channel is 1 (for all conv2d layers). I checked that you have a pre-check that ensuring all channels should be divided by 4. So how do I enable int8 on my model?

Thanks.
-Mingwei

**Comment by vinx13** [comment]
NCHW4c template doesn't work for your case. You can try the NCHW one. (directly use the extracted tasks instead of creating new ones with template key int8)
